### ISSUE TITLE
Dolby TrueHD no Audio

### ISSUE THREAD

**Issue by mok73125** [IDimitrovDev/Energy-Media-Player#14]
Hello i just bought energy media player for windows from the store and it works perfectly with dolby vision but there is one issue when i switch the audio track to dolby truehd 7.1 audio there is no sound but when i switch it to ac-3 5.1 it works fine i have also disabled passthrough dts and it didn't fix it,
Please if this could somehow be fixed this would be the best media player to ever exist. Thank you.

**Comment by mok73125** [comment]
I have disabled Dolby digital passthrough and still no sound, also from what i noticed this problem occurs whenever there is a 7.1 channel audio source because i also had a movie with aac 7.1 and it had no sound and from the other movie with Dolby truehd 7.1 sound there is also no sound from it, i have disabled all the passthrough options for aac and Dolby digital and still nothing.
Do you need any information from me? also i have Dolby Atmos from Dolby access and i want the media player to utilize it so i don't know if when i disable the Dolby digital passthrough if that disables it form utilizing it.

**Comment by IDimitrovDev** [comment]
Do the samples from https://www.demolandia.net/cinema/dolby-demo-trailers-hd/page-6.html?highlight=1 fail to play audio too? Also what does the codec information show as audio codec
![image](https://github.com/user-attachments/assets/c7c41ca5-4b2a-4348-8ffd-861d4d0c68ff)
![image](https://github.com/user-attachments/assets/d47de1dd-4fdb-47a2-bb7c-fd4be343e347)

**Comment by mok73125** [comment]
I apologize for this but after disabling every passthrough option and restarting my pc every 7.1 audio file now works fine and i have no problems, I'm sorry for the hassle.
My only question is does disabling the passthrough mean that I'm losing any quality or it doesn't matter even if i have the Dolby Atmos spatial effect?

**Comment by IDimitrovDev** [comment]
You shouldn't lose any quality as the decoded output should be the same as what the hardware would output if passthrough was supported. The drawback is that the player will use more memory and CPU than if passthrough was available.
 For the next update I'm preparing a separate passthrough option for Dolby TrueHD, to allow enabling passthrough for Dolby Digital but disabling for TrueHD as more often than not devices support Dolby Digital passthrough, but not TrueHD.

**Comment by mok73125** [comment]
Thank you so much, Excited for what you have cooking you have the best media player in my opinion :) .
