### ISSUE TITLE
The frame is cropped sometimes

### ISSUE THREAD

**Issue by iHeadway** [IDimitrovDev/Energy-Media-Player#3]
![yQdHY2T 1](https://github.com/IDimitrovDev/Energy-Media-Player/assets/30590849/0e7006d0-cb89-449e-b999-c5230d8c594b)
The problem persists only with HW (Dolby Vision Profile X) decoder.

**Comment by IDimitrovDev** [comment]
Thank you for reporting the issue. Do you have a sample file where the image is cropped?

**Comment by iHeadway** [comment]
> Do you have a sample file where the image is cropped?
Yes, how can I send it to you?

**Comment by IDimitrovDev** [comment]
If its up to 10MB it can be attached to the issue, if its bigger I would need link to it from some cloud storage where is uploaded(GDrive/Dropbox/Onedrive), which you could send me privately at idimitrov.dev@gmail.com or post here.

**Comment by iHeadway** [comment]
I'm sorry, but I think the issue is with the sample file, not the player.
