### ISSUE TITLE
white pixel on the left middle of the player ui

### ISSUE THREAD

**Issue by nekos95** [IDimitrovDev/Energy-Media-Player#8]
Firstly, great player , thank you for all the effort you put into making it,
There's a white pixel on the left middle of the players ui when playing video . i haven't noticed how long since it appeared due to my tvs pixel shift but i suspect it was introduced in the last update.

is not a part of the video file, doesnt happen in other players and if i resize the window
![Screenshot 2024-08-30 175219](https://github.com/user-attachments/assets/68051af5-d8ea-4016-a269-78d93635494b)
![Screenshot 2024-08-30 175316](https://github.com/user-attachments/assets/8b6c28fc-ec4a-48ff-8a20-6c8a508af461)

**Comment by Midnightspace** [comment]
I have noticed it as well, luckily its only noticable on dark scenes but lets hope that it'll get fixed in a update

**Comment by IDimitrovDev** [comment]
Version v221 is deployed that should be fixing the white pixel issue.

**Comment by nekos95** [comment]
resolved
